title: ClassiPic Privacy Policy
description: How ClassiPic handles your data
theme: jekyll-theme-cayman
permalink: /:basename:output_ext

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
